---
controller_credentials:
  - name: RHDESystems
    description: SSH Key for connecting to RHDE systems
    credential_type: Machine
    organization: "{{ global_organization }}"
    inputs:
      username: "{{ rhde_ssh_user }}"
      ssh_key_data: "{{ lookup('file', ssh_private_key) }}"

  - name: RHDEMGMT
    description: SSH Key for connecting to management systems
    credential_type: Machine
    organization: "{{ global_organization }}"
    inputs:
      username: "{{ mgmt_ssh_user }}"
      ssh_key_data: "{{ lookup('file', mgmt_ssh_private_key) }}"

  - name: RHDEVault
    description: Ansible Vault password to unlock sealed secrets
    credential_type: Vault
    organization: "{{ global_organization }}"
    inputs:
      vault_password: "{{ lookup('file', ansible_vault_password_file) }}"