# podman build -t jobcode-web -f Containerfile.web .
# podman push jobcode-web quay.io/kenmoini/jobcode-web:latest
# podman run --name jobcode-web --rm -it -p 8501:8501 jobcode-web

#FROM registry.fedoraproject.org/fedora:37
FROM quay.io/kenmoini/job-code-base:latest

ENV BACKEND_API="http://localhost:8675"

USER 0

WORKDIR /opt/app-root/src
COPY ./src /opt/app-root/src

RUN chmod a+x /opt/app-root/src/start-web.sh

USER 1001

EXPOSE 8501

CMD ["/opt/app-root/src/start-web.sh"]