# podman build -t jobcode-base -f Containerfile.base .
# podman push jobcode-base quay.io/kenmoini/jobcode-base:latest

FROM registry.fedoraproject.org/fedora:37

USER 0

WORKDIR /opt/app-root/src
COPY ./src /opt/app-root/src

RUN dnf update -y \
 && dnf install -y python3 python3-pip \
 && mkdir -p /opt/app-root/src \
 && pip3 install -r /opt/app-root/src/requirements.txt
