# podman build -t jobcode-web -f Containerfile.web .
# podman push jobcode-web quay.io/kenmoini/jobcode-web:latest
# podman run --name jobcode-web --rm -it -p 8501:8501 jobcode-web

FROM registry.fedoraproject.org/fedora:37

ENV BACKEND_API="http://localhost:8675"

USER 0

WORKDIR /opt/app-root/src
COPY ./src /opt/app-root/src

RUN dnf update -y \
 && dnf install -y python3 python3-pip \
 && mkdir -p /opt/app-root/src \
 && pip3 install -r /opt/app-root/src/requirements.txt

USER 1001

EXPOSE 8501

CMD ["/opt/app-root/src/start-web.sh"]