---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.9
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

images:
  base_image:
    #name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest
    name: quay.io/centos/centos:stream9

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"

#options:
#  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: ansible.cfg
    dest: configs

additional_build_steps:
  append_final: |
    RUN curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar -xvzf - -C /usr/local/bin/ oc kubectl && chmod 755 /usr/local/bin/oc && chmod 755 /usr/local/bin/kubectl \
    && curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  prepend_final: |
    RUN dnf install -y 'dnf-command(config-manager)' \
    && rpm --import https://packages.microsoft.com/keys/microsoft.asc \
    && rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    && /usr/bin/crb enable \
    && dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm \
    && dnf update -y && dnf install git azure-cli -y && dnf clean all && ansible --version \
    && az extension add --name connectedk8s \
    && az extension add --name k8s-configuration
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - RUN dnf install -y git && dnf clean all
  prepend_base:
    - RUN dnf install -y git && dnf clean all
  prepend_builder:
    - RUN dnf install -y git && dnf clean all && python3 -m pip install --upgrade pip