---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.9
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

images:
  base_image:
    #name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest
    name: quay.io/centos/centos:stream9

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"

#options:
#  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: ansible.cfg
    dest: configs

additional_build_steps:
  prepend_final: |
    RUN dnf install -y 'dnf-command(config-manager)' && rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && /usr/bin/crb enable && dnf update -y && dnf install git -y && dnf clean all && ansible --version
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - RUN dnf install -y git && dnf clean all
  prepend_base:
    - RUN dnf install -y git && dnf clean all
  prepend_builder:
    - RUN dnf install -y git && dnf clean all && python3 -m pip install --upgrade pip