---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-app-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  frontend-connection.js: |
    var apiEndpoint = "https://ocr-api.apps.ocp4.example.com/createJobCodeClaim";
