---
# This actually isn't used or complete since the ostree mirror processes are part of the create-blueprints.yml playbook
- name: Create an OSTree Repo
  hosts: ostreemirror
  become: yes

  vars:
    packages:
      - createrepo_c

  tasks:
    - name: Install required packages
      package:
        name: "{{ packages }}"
        state: present