---
- name: Configure PXE Server for specific MAC Address boots
  hosts: pxeserver
  become: yes

  vars:
    # iso_name: rhde-si.iso # taken from input
    # mac_address: "" # taken from input

    mac_address_dashes_lower: "{{ mac_address | lower | regex_replace(':', '-') }}"

    pxe_server_ip: 192.168.99.10
    httpd_server_ip: 192.168.99.12

    pxe_server_path: /var/ftp/pub/pxe
    tftp_sub_path: tftpboot
    install_file_sub_path: install
    architecture: x86_64 # x86_64 or aarch64
    boot_architecture: EFI # BIOS or EFI

    iso_base_name: "{{ iso_name | replace('.iso', '') }}"
    distro_key: "{{ iso_name | replace('.iso', '') | replace('.', '') | replace('-', '') | replace('_', '') }}"
    distro_arch_key: "{{ distro_key }}{{ architecture | replace('_', '') }}"
    iso_path: "{{ pxe_server_path }}/install/{{ architecture }}/{{ distro_key }}/iso"
    
    # /var/ftp/pub/pxe/install/x86_64/minimalrhel94/ext
    extract_iso_path: "{{ pxe_server_path }}/install/{{ architecture }}/{{ distro_key }}/ext"
    # /var/ftp/pub/pxe/install/x86_64/minimalrhel94/ext/minimal-rhel94
    extract_iso_base_path: "{{ pxe_server_path }}/install/{{ architecture }}/{{ distro_key }}/ext/{{ iso_base_name }}/{{ iso_base_name }}"

    # /var/ftp/pub/pxe/tftpboot/EFI/x86_64/rhel94/rhel94x8664
    efi_pxe_config_path: "{{ pxe_server_path }}/{{ tftp_sub_path }}/EFI/{{ architecture }}"
    bios_pxe_config_path: "{{ pxe_server_path }}/{{ tftp_sub_path }}/BIOS/{{ architecture }}/pxelinux.cfg"

  tasks:
    - name: Copy over grub config file from the extracted ISO
      ansible.builtin.copy:
        src: "{{ extract_iso_base_path }}/EFI/BOOT/grub.cfg"
        dest: "{{ efi_pxe_config_path }}/grub.cfg-01-{{ mac_address_dashes_lower }}"
        mode: 0644
        remote_src: yes

    - name: Replace values in the file
      ansible.builtin.replace:
        path: "{{ efi_pxe_config_path }}/grub.cfg-01-{{ mac_address_dashes_lower }}"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - regexp: 'initrd /images/pxeboot/initrd.img'
          replace: "initrd /{{ boot_architecture }}/{{ architecture }}/{{ distro_key }}/{{ iso_base_name }}/initrd.img"
        - regexp: 'linux /images/pxeboot/vmlinuz'
          replace: "linux /{{ boot_architecture }}/{{ architecture }}/{{ distro_key }}/{{ iso_base_name }}/vmlinuz"
        - regexp: 'timeout=60'
          replace: 'timeout=5'
        - regexp: 'image_file=/run/media/iso/image.raw.xz'
          replace: 'image_url=http://{{ httpd_server_ip }}/pxe/install/{{ architecture }}/{{ distro_key }}/ext/{{ iso_base_name }}/image.raw.xz'

    #- name: Template EFI Boot Configuration
    #  template:
    #    src: templates/per-mac-efi-grub.cfg.j2
    #    dest: "{{ efi_pxe_config_path }}/grub.cfg-01-{{ mac_address_dashes_lower }}"
    #    mode: 0644

    #- name: Template BIOS Boot Configuration because why not
    #  template:
    #    src: templates/per-mac-bios-pxelinux.cfg.j2
    #    dest: "{{ bios_pxe_config_path }}/01-{{ mac_address_dashes_lower }}"
    #    mode: 0644

    - name: Template PXELinux Menu defaults
      template:
        src: templates/pxe-menu-defaults.cfg.j2
        dest: "{{ bios_pxe_config_path }}/pxe-menu-defaults.cfg"
        mode: 0644