---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  labels:
    app: scanner
  name: scanner
spec:
  to:
    kind: Service
    name: scanner
    weight: 100
  port:
    targetPort: scanner
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
