name: EE build and deploy

on:
  pull_request:
    paths:
      - 'ansible/execution-environment/**'
  push:
    branches:
      - main
    paths:
      - 'ansible/execution-environment/**'

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    #uses: kenmoini/ocp4-ai-svc-universal/.github/workflows/base-build-deploy-ee.yml@main
    uses: kenmoini/ansible-ee-builder/.github/workflows/build-ee-base.yml@main
    with:
      EE_FOLDER_NAME: 'ansible/execution-environment'
      EE_IMAGE_NAME: 'rhde-ztp-ee'
      EE_IMAGE_TAG: 'latest'
    secrets:
      REGISTRY_HOSTNAME: quay.io
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
      REGISTRY_PATH: kenmoini
      # REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      # REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      # AH_TOKEN: ${{ secrets.AH_TOKEN }}